export const list = ["Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam", "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "New Delhi",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"]

export const citylist = {
    "Andaman and Nicobar Islands": ["Andaman and Nicobar Islands"],
    "Andhra Pradesh": ["Visakhapatnam","Vijayawada","Guntur","Nellore","Kurnool","Kakinada","Rajahmundry","Kadapa","Mangalagiri-Tadepalli","Tirupati","Anantapuram","Vizianagaram","Eluru","Nandyal","Ongole","Adoni","Madanapalle","Machilipatnam","Tenali","Proddatur","Chittoor","Hindupur","Srikakulam","	Bhimavaram","Tadepalligudem","Guntakal","Dharmavaram","Gudivada","Narasaraopet","Kadiri","Tadipatri","Chilakaluripet"],
    "Arunachal Pradesh": ["Anjaw","Changlang","Dibang Valley","East Kameng","East Siang","Kurung Kumey","Lohit","Lower Dibang Valley","Lower Subansiri","Papum Pare","Tawang","Tirap","Upper Siang","Upper Subansiri","West Kameng","West Siang"],
    "Assam": ["Guwahati","Silchar","Dibrugarh","Jorhat","Bongaigaon","Tinsukia","Tezpur"],
    "Bihar": ["Patna","Gaya","Bhagalpur","Muzaffarpur","Bihar Sharif","Darbhanga","Purnia","Sasaram","Arrah","Samastipur","Madhubani","Siwan","Chhapra","Munger","Saharsa","Motihari","Bettiah","Begusarai","Katihar"],
    "Chandigarh": ["Chandigarh"],
    "Chhattisgarh": ["Raipur","Bhilai","Bilaspur","Korba","Raj Nandgaon","Raigarh","Jagdalpur","	Ambikapur","Dhamtari","Chirmiri","Bhatapara","Mahasamund","Dalli-Rajhara","Kawardha","Champa","Naila Janjgir","Kanker","Dongragarh","Tilda Neora","Mungeli","Manendragarh","Kondagaon","Gobranawapara","Bemetara","Baikunthpur"],
    "Dadra and Nagar Haveli and Daman and Diu": ["Dadra and Nagar Haveli and Daman and Diu"],
    "Goa": ["Bicholim","Canacona","Cuncolim","Curchorem","Mapusa","Margao","Mormugao","Panaji","Pernem","Ponda","Quepem","Sanguem","Sanquelim","Valpoi"],
    "Gujarat": ["Surat","Ahmedabad","Vadodara","Rajkot","Bhavnagar","Jamnagar","Gandhinagar","Junagadh","Gandhidham","Anand","Navsari","Morbi","Nadiad","Surendranagar","Bharuch","Mehsana","Bhuj","	Porbandar","Palanpur","Valsad","Vapi","Gondal","Veraval","Godhra","Patan","Kalol","Botad","Amreli","Deesa","Jetpur"],
    "Haryana" : ["Faridabad","Gurugram","Panipat","Ambala","Yamunanagar","Rohtak","Hisar","Karnal","Sonipat","Panchkula","Sirsa","Bhiwani","Bahadurgarh","Jind","Thanesar","Kaithal","Rewari","	Palwal","Hansi","	Narnaul"],
    "Himachal Pradesh" : ["Bilaspur","Chamba","Hamirpur","Kangra","Kinnaur","Kullu","Lahul & Spiti","Mandi","Shimla","Sirmaur","Solan","Una"],
    "Jammu and Kashmir":["Anantnag","Badgam","Bandipore","Baramula","Doda","Ganderbal","Jammu","Kathua","Kishtwar","Kulgam","Kupwara","Pulwama","Punch","Rajouri","Ramban","Reasi","Samba","Shupiyan","Srinagar","Udhampur"],
    "Jharkhand":["Bokaro","Chatra","Deoghar","Dhanbad","Dumka","Garhwa","Giridih","Godda","Gumla","Hazaribagh","Jamtara","Khunti","Kodarma","Latehar","Lohardaga","Pakur","Palamu","Pashchimi Singhbhum(West Singhbhum)","Purbi Singhbhum (East Singhbhum)","Ramgarh","Ranchi","Sahibganj","Saraikela-Kharsawan","Simdega"],
    "Karnataka": ["Bagalkot","Ballari (Bellary)","Belagavi (Belgaum)","Bengaluru (Bangalore)","Bidar","Chamarajanagar","Chikballapur", "Chikkamagaluru (Chikmagalur)","Chitradurga","Dakshina Kannada","Davanagere","Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi (Gulbarga)","Kodagu (Coorg)", "Kolar", "Koppal","Mandya","Mysuru (Mysore)", "Raichur","Ramanagara", "Shivamogga (Shimoga)","Tumakuru (Tumkur)","Udupi","Uttara Kannada (Karwar)", "Vijayapura (Bijapur)", "Yadgir",],
    "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur", "Alappuzha", "Palakkad", "Kottayam", "Malappuram", "Kannur", "Kasaragod", "Pathanamthitta", "Idukki", "Ernakulam", "Wayanad"],
    "Ladakh":["Leh", "Kargil"],
    "Lakshadweep":["Kavaratti", "Agatti", "Bangaram", "Andrott", "Kalpeni", "Minicoy", "Amini", "Bitra", "Chetlat", "Kadmat", "Kiltan", "Lakshadweep", "Suheli Par", "Suheli Cheriyam", "Suheli Valiyam"],
    "Madhya Pradesh":[ "Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Dewas", "Satna", "Ratlam", "Rewa", "Katni", "Singrauli", "Burhanpur", "Khandwa", "Bhind", "Chhindwara", "Guna", "Shivpuri", "Vidisha","Chhatarpur", "Damoh", "Mandsaur", "Khargone", "Neemuch", "Pithampur", "Narmadapuram", "Itarsi", "Sehore", "Chambal[2]", "Betul", "Seoni", "Datia", "Nagda", "Dindori"],
    "Maharashtra":["Mumbai City", "Mumbai Suburban", "Thane", "Palghar", "Raigad", "Ratnagiri", "Sindhudurg", "Nashik", "Dhule", "Nandurbar", "Jalgaon", "Ahmednagar", "Pune", "Solapur", "Satara", "Sangli", "Kolhapur", "Aurangabad", "Jalna", "Beed", "Osmanabad", "Nanded", "Parbhani", "Hingoli", "Latur", "Buldhana", "Akola", "Washim", "Amravati", "Yavatmal", "Nagpur", "Bhandara", "Gondia", "Chandrapur", "Gadchiroli"],
    "Manipur": [ "Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West", "Jiribam", "Kakching", "Kamjong", "Kangpokpi", "Noney", "Pherzawl", "Senapati", "Tamenglong", "Tengnoupal", "Thoubal", "Ukhrul"],
    "Meghalaya":  ["East Garo Hills", "West Garo Hills", "South Garo Hills", "North Garo Hills", "East Khasi Hills", "West Khasi Hills", "South West Khasi Hills", "Ri-Bhoi", "East Jaintia Hills", "West Jaintia Hills"],
    "Mizoram": ["Aizawl", "Lunglei", "Saiha", "Champhai", "Serchhip", "Kolasib", "Lawngtlai", " Mamit"],
    "New Delhi":["New Delhi"],
    "Nagaland":[ "Dimapur", "Kohima", "Mokokchung", "Mon", "Phek", "Tuensang", "Wokha", "Zunheboto"],
    "Odisha": ["Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghpur", "Jajpur", "Jharsuguda", "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar (Keonjhar)", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Subarnapur (Sonepur)", "Sundargarh"],
    "Puducherry": ["Puducherry", "Karaikal", "Yanam", "Mahe"],
    "Punjab":["Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Moga", "Muktsar", "Pathankot", "Patiala", "Rupnagar", "Sahibzada Ajit Singh Nagar", "Sangrur", "Shahid Bhagat Singh Nagar", "Sri Muktsar Sahib", "Tarn Taran"],
    "Rajasthan":[ "Ajmer", "Alwar", "Banswara", "Baran", "Barmer", "Bharatpur", "Bhilwara","Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur","Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur","Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur","Sikar", "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur"],
    "Sikkim":[ "East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
    "Tamil Nadu": ["Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri","Dindigul", "Erode", "Kallakurichi", "Kanchipuram", "Kanyakumari", "Karur", "Krishnagiri","Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai","Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi","Tiruchirappalli", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai","Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar"],
    "Telangana":["Adilabad", "Bhadradri Kothagudem", "Hyderabad", "Jagtial", "Jangaon", "Jayashankar Bhupalapally","Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam", "Komaram Bheem", "Mahabubabad","Mahabubnagar", "Mancherial", "Medak", "Medchal–Malkajgiri", "Nagarkurnool", "Nalgonda", "Nirmal","Nizamabad", "Peddapalli", "Rajanna Sircilla", "Rangareddy", "Sangareddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", "Yadadri Bhuvanagiri"],
    "Tripura":[ "Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"],
    "Uttar Pradesh":["Agra", "Aligarh", "Ambedkar Nagar", "Ayodhya", "Amethi", "Amroha", "Auraiya", "Azamgarh","Badaun", "Bagpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", "Bareilly","Basti", "Bijnor", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria", "Etah", "Etawah","Farrukhabad", "Fatehpur", "Firozabad", "Gautam Buddha Nagar", "Ghaziabad", "Ghazipur", "Gonda","Gorakhpur", "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj","Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi", "Kushinagar", "Lakhimpur Kheri", "Lalitpur","Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur", "Moradabad","Muzaffarnagar", "Pilibhit", "Pratapgarh", "Prayagraj", "Rae Bareli", "Rampur", "Saharanpur", "Sant Kabir Nagar", "Sant Ravidas Nagar", "Sambhal", "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar","Sitapur", "Sonbhadra", "Sultanpur", "Unnao", "Varanasi"],
    "Uttarakhand":[ "Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"],
    "West Bengal":["Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly","Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia","North 24 Parganas", "Paschim Bardhaman", "Paschim Medinipur", "Purba Bardhaman", "Purba Medinipur","Purulia", "South 24 Parganas", "Uttar Dinajpur"]
}

export const deptlist = ['Municipal Cooperation','CyberSecurity Department','Electricity Department']